# Generated by Django 5.1.1 on 2024-10-17 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('attendee_phone', models.CharField(max_length=15)),
                ('parent_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('pick_up_location', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=9)),
                ('qr_code_path', models.FilePathField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
