# Generated by Django 5.1.1 on 2024-10-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyfest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='pick_up_location',
            new_name='pickup_location',
        ),
    ]
