# Generated by Django 5.1.1 on 2024-10-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyfest', '0002_rename_pick_up_location_attendee_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='qr_code_path',
        ),
    ]
